# Generated by Django 5.2.13 on 2026-04-14 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('elementary', 'Элементарный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('study_streak', models.IntegerField(default=0)),
                ('words_learned', models.IntegerField(default=0)),
                ('hours_studied', models.FloatField(default=0.0)),
                ('daily_goal', models.CharField(default='30 минут', help_text='Ежедневная цель обучения', max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('dark_theme', models.BooleanField(default=False)),
                ('show_tips', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
